// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import type {
  AuthAuthJwtLoginData,
  AuthAuthJwtLoginResponses,
  AuthAuthJwtLoginErrors,
  AuthAuthJwtLogoutData,
  AuthAuthJwtLogoutResponses,
  AuthAuthJwtLogoutErrors,
  AuthRegisterRegisterData,
  AuthRegisterRegisterResponses,
  AuthRegisterRegisterErrors,
  AuthResetForgotPasswordData,
  AuthResetForgotPasswordResponses,
  AuthResetForgotPasswordErrors,
  AuthResetResetPasswordData,
  AuthResetResetPasswordResponses,
  AuthResetResetPasswordErrors,
  AuthVerifyRequestTokenData,
  AuthVerifyRequestTokenResponses,
  AuthVerifyRequestTokenErrors,
  AuthVerifyVerifyData,
  AuthVerifyVerifyResponses,
  AuthVerifyVerifyErrors,
  UsersUsersCurrentUserData,
  UsersUsersCurrentUserResponses,
  UsersUsersCurrentUserErrors,
  UsersUsersPatchCurrentUserData,
  UsersUsersPatchCurrentUserResponses,
  UsersUsersPatchCurrentUserErrors,
  UsersUsersDeleteUserData,
  UsersUsersDeleteUserResponses,
  UsersUsersDeleteUserErrors,
  UsersUsersUserData,
  UsersUsersUserResponses,
  UsersUsersUserErrors,
  UsersUsersPatchUserData,
  UsersUsersPatchUserResponses,
  UsersUsersPatchUserErrors,
  HealthHealthData,
  HealthHealthResponses,
  ItemReadItemData,
  ItemReadItemResponses,
  ItemReadItemErrors,
  ItemCreateItemData,
  ItemCreateItemResponses,
  ItemCreateItemErrors,
  ItemDeleteItemData,
  ItemDeleteItemResponses,
  ItemDeleteItemErrors,
  PositionsGetPositionsData,
  PositionsGetPositionsResponses,
  PositionsGetPositionsErrors,
  PositionsGetStockPositionsData,
  PositionsGetStockPositionsResponses,
  PositionsGetStockPositionsErrors,
  PositionsGetWarrantPositionsData,
  PositionsGetWarrantPositionsResponses,
  PositionsGetWarrantPositionsErrors,
  PositionsGetBondPositionsData,
  PositionsGetBondPositionsResponses,
  PositionsGetBondPositionsErrors,
  PositionsGetTradeSummaryData,
  PositionsGetTradeSummaryResponses,
  PositionsGetTradeSummaryErrors,
  PnlGetPnlChangesData,
  PnlGetPnlChangesResponses,
  PnlGetPnlChangesErrors,
  PnlGetPnlSummaryData,
  PnlGetPnlSummaryResponses,
  PnlGetPnlSummaryErrors,
  PnlGetPnlByCurrencyData,
  PnlGetPnlByCurrencyResponses,
  PnlGetPnlByCurrencyErrors,
  PnlGetPnlFullData,
  PnlGetPnlFullResponses,
  PnlGetPnlFullErrors,
  PnlGetKpiMetricsData,
  PnlGetKpiMetricsResponses,
  MarketDataGetMarketDataData,
  MarketDataGetMarketDataResponses,
  MarketDataGetFxDataData,
  MarketDataGetFxDataResponses,
  MarketDataGetTopMoversData,
  MarketDataGetTopMoversResponses,
  MarketDataGetTopMoversErrors,
  MarketDataGetTradingCalendarData,
  MarketDataGetTradingCalendarResponses,
  MarketDataGetTradingCalendarErrors,
  MarketDataGetMarketHoursData,
  MarketDataGetMarketHoursResponses,
  MarketDataGetTickerDataData,
  MarketDataGetTickerDataResponses,
  MarketDataGetHistoricalDataData,
  MarketDataGetHistoricalDataResponses,
  MarketDataGetHistoricalDataErrors,
  MarketDataGetStockDataData,
  MarketDataGetStockDataResponses,
  MarketDataGetStockDataErrors,
  MarketDataGetStockHistoryData,
  MarketDataGetStockHistoryResponses,
  MarketDataGetStockHistoryErrors,
  MarketDataGetStockNewsData,
  MarketDataGetStockNewsResponses,
  MarketDataGetStockNewsErrors,
  RiskGetDeltaChangeData,
  RiskGetDeltaChangeResponses,
  RiskGetDeltaChangeErrors,
  RiskGetRiskMeasuresData,
  RiskGetRiskMeasuresResponses,
  RiskGetRiskMeasuresErrors,
  RiskGetRiskInputsData,
  RiskGetRiskInputsResponses,
  RiskGetRiskInputsErrors,
  RiskPriceWarrantData,
  RiskPriceWarrantResponses,
  RiskPriceWarrantErrors,
  RiskPriceBondData,
  RiskPriceBondResponses,
  RiskPriceBondErrors,
  ComplianceGetRestrictedListData,
  ComplianceGetRestrictedListResponses,
  ComplianceGetUndertakingsData,
  ComplianceGetUndertakingsResponses,
  ComplianceGetUndertakingsErrors,
  ComplianceGetBeneficialOwnershipData,
  ComplianceGetBeneficialOwnershipResponses,
  ComplianceGetBeneficialOwnershipErrors,
  ComplianceGetMonthlyExerciseLimitData,
  ComplianceGetMonthlyExerciseLimitResponses,
  ComplianceGetMonthlyExerciseLimitErrors,
  ReconciliationGetPpsReconData,
  ReconciliationGetPpsReconResponses,
  ReconciliationGetPpsReconErrors,
  ReconciliationGetSettlementReconData,
  ReconciliationGetSettlementReconResponses,
  ReconciliationGetSettlementReconErrors,
  ReconciliationGetFailedTradesData,
  ReconciliationGetFailedTradesResponses,
  ReconciliationGetFailedTradesErrors,
  ReconciliationGetPnlReconData,
  ReconciliationGetPnlReconResponses,
  ReconciliationGetPnlReconErrors,
  ReconciliationGetRiskInputReconData,
  ReconciliationGetRiskInputReconResponses,
  ReconciliationGetRiskInputReconErrors,
  PortfolioToolsGetPayToHoldData,
  PortfolioToolsGetPayToHoldResponses,
  PortfolioToolsGetPayToHoldErrors,
  PortfolioToolsGetStockBorrowData,
  PortfolioToolsGetStockBorrowResponses,
  PortfolioToolsGetResetDatesData,
  PortfolioToolsGetResetDatesResponses,
  PortfolioToolsGetComingResetsData,
  PortfolioToolsGetComingResetsResponses,
  PortfolioToolsGetCbInstallmentsData,
  PortfolioToolsGetCbInstallmentsResponses,
  PortfolioToolsGetCbInstallmentsErrors,
  PortfolioToolsGetExcessAmountData,
  PortfolioToolsGetExcessAmountResponses,
  PortfolioToolsGetExcessAmountErrors,
  PortfolioToolsGetDealIndicationData,
  PortfolioToolsGetDealIndicationResponses,
  PortfolioToolsGetPoSettlementData,
  PortfolioToolsGetPoSettlementResponses,
  PortfolioToolsGetPoSettlementErrors,
  PortfolioToolsGetShortEclData,
  PortfolioToolsGetShortEclResponses,
  InstrumentsGetTickerDataData,
  InstrumentsGetTickerDataResponses,
  InstrumentsGetStockScreenerData,
  InstrumentsGetStockScreenerResponses,
  InstrumentsGetSpecialTermsData,
  InstrumentsGetSpecialTermsResponses,
  InstrumentsGetSpecialTermsErrors,
  InstrumentsGetInstrumentDataData,
  InstrumentsGetInstrumentDataResponses,
  InstrumentsGetInstrumentTermData,
  InstrumentsGetInstrumentTermResponses,
  EventsGetEventCalendarData,
  EventsGetEventCalendarResponses,
  EventsGetEventCalendarErrors,
  EventsGetEventStreamData,
  EventsGetEventStreamResponses,
  EventsGetReverseInquiriesData,
  EventsGetReverseInquiriesResponses,
  EventsGetReverseInquiriesErrors,
  OperationsGetDailyProceduresData,
  OperationsGetDailyProceduresResponses,
  OperationsGetOperationProcessesData,
  OperationsGetOperationProcessesResponses,
  OperationsRerunProcessData,
  OperationsRerunProcessResponses,
  OperationsRerunProcessErrors,
  OperationsKillProcessData,
  OperationsKillProcessResponses,
  OperationsKillProcessErrors,
  OrdersGetOrdersData,
  OrdersGetOrdersResponses,
  OrdersGetOrderRoutesData,
  OrdersGetOrderRoutesResponses,
  OrdersGetOrderRoutesErrors,
  PerformanceGetKpiDataData,
  PerformanceGetKpiDataResponses,
  PerformanceGetTopMoversData,
  PerformanceGetTopMoversResponses,
  PerformanceGetPortfolioHoldingsData,
  PerformanceGetPortfolioHoldingsResponses,
  NotificationsGetNotificationsData,
  NotificationsGetNotificationsResponses,
  NotificationsGetNotificationsErrors,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authAuthJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthAuthJwtLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthAuthJwtLoginResponses,
    AuthAuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authAuthJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthAuthJwtLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthAuthJwtLogoutResponses,
    AuthAuthJwtLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/logout",
    ...options,
  });
};

/**
 * Register:Register
 */
export const authRegisterRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthRegisterRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthRegisterRegisterResponses,
    AuthRegisterRegisterErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Forgot Password
 */
export const authResetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthResetForgotPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthResetForgotPasswordResponses,
    AuthResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Reset Password
 */
export const authResetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthResetResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthResetResetPasswordResponses,
    AuthResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Request-Token
 */
export const authVerifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<AuthVerifyRequestTokenData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthVerifyRequestTokenResponses,
    AuthVerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Verify
 */
export const authVerifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<AuthVerifyVerifyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthVerifyVerifyResponses,
    AuthVerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Current User
 */
export const usersUsersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersUsersCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersUsersCurrentUserResponses,
    UsersUsersCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Users:Patch Current User
 */
export const usersUsersPatchCurrentUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersUsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersUsersPatchCurrentUserResponses,
    UsersUsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Delete User
 */
export const usersUsersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersUsersDeleteUserResponses,
    UsersUsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:User
 */
export const usersUsersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersUsersUserResponses,
    UsersUsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:Patch User
 */
export const usersUsersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUsersPatchUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersUsersPatchUserResponses,
    UsersUsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Health
 */
export const healthHealth = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthHealthResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/health",
    ...options,
  });
};

/**
 * Read Item
 */
export const itemReadItem = <ThrowOnError extends boolean = false>(
  options?: Options<ItemReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ItemReadItemResponses,
    ItemReadItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/",
    ...options,
  });
};

/**
 * Create Item
 */
export const itemCreateItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemCreateItemData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ItemCreateItemResponses,
    ItemCreateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item
 */
export const itemDeleteItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemDeleteItemData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    ItemDeleteItemResponses,
    ItemDeleteItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{item_id}",
    ...options,
  });
};

/**
 * Get Positions
 */
export const positionsGetPositions = <ThrowOnError extends boolean = false>(
  options?: Options<PositionsGetPositionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionsGetPositionsResponses,
    PositionsGetPositionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/positions/",
    ...options,
  });
};

/**
 * Get Stock Positions
 */
export const positionsGetStockPositions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PositionsGetStockPositionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionsGetStockPositionsResponses,
    PositionsGetStockPositionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/positions/stocks",
    ...options,
  });
};

/**
 * Get Warrant Positions
 */
export const positionsGetWarrantPositions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PositionsGetWarrantPositionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionsGetWarrantPositionsResponses,
    PositionsGetWarrantPositionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/positions/warrants",
    ...options,
  });
};

/**
 * Get Bond Positions
 */
export const positionsGetBondPositions = <ThrowOnError extends boolean = false>(
  options?: Options<PositionsGetBondPositionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionsGetBondPositionsResponses,
    PositionsGetBondPositionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/positions/bonds",
    ...options,
  });
};

/**
 * Get Trade Summary
 */
export const positionsGetTradeSummary = <ThrowOnError extends boolean = false>(
  options?: Options<PositionsGetTradeSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionsGetTradeSummaryResponses,
    PositionsGetTradeSummaryErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/positions/trade-summary",
    ...options,
  });
};

/**
 * Get Pnl Changes
 */
export const pnlGetPnlChanges = <ThrowOnError extends boolean = false>(
  options?: Options<PnlGetPnlChangesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PnlGetPnlChangesResponses,
    PnlGetPnlChangesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/pnl/changes",
    ...options,
  });
};

/**
 * Get Pnl Summary
 */
export const pnlGetPnlSummary = <ThrowOnError extends boolean = false>(
  options?: Options<PnlGetPnlSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PnlGetPnlSummaryResponses,
    PnlGetPnlSummaryErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/pnl/summary",
    ...options,
  });
};

/**
 * Get Pnl By Currency
 */
export const pnlGetPnlByCurrency = <ThrowOnError extends boolean = false>(
  options?: Options<PnlGetPnlByCurrencyData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PnlGetPnlByCurrencyResponses,
    PnlGetPnlByCurrencyErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/pnl/currency",
    ...options,
  });
};

/**
 * Get Pnl Full
 */
export const pnlGetPnlFull = <ThrowOnError extends boolean = false>(
  options?: Options<PnlGetPnlFullData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PnlGetPnlFullResponses,
    PnlGetPnlFullErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/pnl/full",
    ...options,
  });
};

/**
 * Get Kpi Metrics
 */
export const pnlGetKpiMetrics = <ThrowOnError extends boolean = false>(
  options?: Options<PnlGetKpiMetricsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PnlGetKpiMetricsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/pnl/kpi",
    ...options,
  });
};

/**
 * Get Market Data
 */
export const marketDataGetMarketData = <ThrowOnError extends boolean = false>(
  options?: Options<MarketDataGetMarketDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketDataGetMarketDataResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/",
    ...options,
  });
};

/**
 * Get Fx Data
 */
export const marketDataGetFxData = <ThrowOnError extends boolean = false>(
  options?: Options<MarketDataGetFxDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketDataGetFxDataResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/fx",
    ...options,
  });
};

/**
 * Get Top Movers
 */
export const marketDataGetTopMovers = <ThrowOnError extends boolean = false>(
  options?: Options<MarketDataGetTopMoversData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketDataGetTopMoversResponses,
    MarketDataGetTopMoversErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/top-movers",
    ...options,
  });
};

/**
 * Get Trading Calendar
 */
export const marketDataGetTradingCalendar = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MarketDataGetTradingCalendarData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketDataGetTradingCalendarResponses,
    MarketDataGetTradingCalendarErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/trading-calendar",
    ...options,
  });
};

/**
 * Get Market Hours
 */
export const marketDataGetMarketHours = <ThrowOnError extends boolean = false>(
  options?: Options<MarketDataGetMarketHoursData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketDataGetMarketHoursResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/market-hours",
    ...options,
  });
};

/**
 * Get Ticker Data
 */
export const marketDataGetTickerData = <ThrowOnError extends boolean = false>(
  options?: Options<MarketDataGetTickerDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketDataGetTickerDataResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/ticker",
    ...options,
  });
};

/**
 * Get Historical Data
 */
export const marketDataGetHistoricalData = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MarketDataGetHistoricalDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketDataGetHistoricalDataResponses,
    MarketDataGetHistoricalDataErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/historical",
    ...options,
  });
};

/**
 * Get Stock Data
 */
export const marketDataGetStockData = <ThrowOnError extends boolean = false>(
  options: Options<MarketDataGetStockDataData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    MarketDataGetStockDataResponses,
    MarketDataGetStockDataErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/stock/{symbol}",
    ...options,
  });
};

/**
 * Get Stock History
 */
export const marketDataGetStockHistory = <ThrowOnError extends boolean = false>(
  options: Options<MarketDataGetStockHistoryData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    MarketDataGetStockHistoryResponses,
    MarketDataGetStockHistoryErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/stock/{symbol}/history",
    ...options,
  });
};

/**
 * Get Stock News
 */
export const marketDataGetStockNews = <ThrowOnError extends boolean = false>(
  options: Options<MarketDataGetStockNewsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    MarketDataGetStockNewsResponses,
    MarketDataGetStockNewsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/market-data/stock/{symbol}/news",
    ...options,
  });
};

/**
 * Get Delta Change
 */
export const riskGetDeltaChange = <ThrowOnError extends boolean = false>(
  options?: Options<RiskGetDeltaChangeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RiskGetDeltaChangeResponses,
    RiskGetDeltaChangeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/risk/delta-change",
    ...options,
  });
};

/**
 * Get Risk Measures
 */
export const riskGetRiskMeasures = <ThrowOnError extends boolean = false>(
  options?: Options<RiskGetRiskMeasuresData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RiskGetRiskMeasuresResponses,
    RiskGetRiskMeasuresErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/risk/measures",
    ...options,
  });
};

/**
 * Get Risk Inputs
 */
export const riskGetRiskInputs = <ThrowOnError extends boolean = false>(
  options?: Options<RiskGetRiskInputsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RiskGetRiskInputsResponses,
    RiskGetRiskInputsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/risk/inputs",
    ...options,
  });
};

/**
 * Price Warrant
 * Run the warrant pricer with the 21 Term + 7 Simulation inputs.
 *
 * Mirrors the Reflex `pricer_warrant_view` calculate handler. The chart
 * series is the 2D payoff curve (Spot vs Value/Delta/Gamma) computed
 * by `WarrantPricer.generate_payoff_curve`.
 */
export const riskPriceWarrant = <ThrowOnError extends boolean = false>(
  options: Options<RiskPriceWarrantData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RiskPriceWarrantResponses,
    RiskPriceWarrantErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/risk/pricer/warrant",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Price Bond
 * Run the convertible-bond pricer with the full Term + Simulation set.
 *
 * Mirrors the Reflex `pricer_bond_view` calculate handler. The chart
 * series is the 2D yield-vs-maturity (or other axis pair) curve.
 */
export const riskPriceBond = <ThrowOnError extends boolean = false>(
  options: Options<RiskPriceBondData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RiskPriceBondResponses,
    RiskPriceBondErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/risk/pricer/bond",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Restricted List
 */
export const complianceGetRestrictedList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ComplianceGetRestrictedListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ComplianceGetRestrictedListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/compliance/restricted-list",
    ...options,
  });
};

/**
 * Get Undertakings
 */
export const complianceGetUndertakings = <ThrowOnError extends boolean = false>(
  options?: Options<ComplianceGetUndertakingsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ComplianceGetUndertakingsResponses,
    ComplianceGetUndertakingsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/compliance/undertakings",
    ...options,
  });
};

/**
 * Get Beneficial Ownership
 */
export const complianceGetBeneficialOwnership = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ComplianceGetBeneficialOwnershipData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ComplianceGetBeneficialOwnershipResponses,
    ComplianceGetBeneficialOwnershipErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/compliance/beneficial-ownership",
    ...options,
  });
};

/**
 * Get Monthly Exercise Limit
 */
export const complianceGetMonthlyExerciseLimit = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ComplianceGetMonthlyExerciseLimitData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ComplianceGetMonthlyExerciseLimitResponses,
    ComplianceGetMonthlyExerciseLimitErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/compliance/monthly-exercise-limit",
    ...options,
  });
};

/**
 * Get Pps Recon
 */
export const reconciliationGetPpsRecon = <ThrowOnError extends boolean = false>(
  options?: Options<ReconciliationGetPpsReconData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReconciliationGetPpsReconResponses,
    ReconciliationGetPpsReconErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/recon/pps",
    ...options,
  });
};

/**
 * Get Settlement Recon
 */
export const reconciliationGetSettlementRecon = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReconciliationGetSettlementReconData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReconciliationGetSettlementReconResponses,
    ReconciliationGetSettlementReconErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/recon/settlement",
    ...options,
  });
};

/**
 * Get Failed Trades
 */
export const reconciliationGetFailedTrades = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReconciliationGetFailedTradesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReconciliationGetFailedTradesResponses,
    ReconciliationGetFailedTradesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/recon/failed-trades",
    ...options,
  });
};

/**
 * Get Pnl Recon
 */
export const reconciliationGetPnlRecon = <ThrowOnError extends boolean = false>(
  options?: Options<ReconciliationGetPnlReconData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReconciliationGetPnlReconResponses,
    ReconciliationGetPnlReconErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/recon/pnl",
    ...options,
  });
};

/**
 * Get Risk Input Recon
 */
export const reconciliationGetRiskInputRecon = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReconciliationGetRiskInputReconData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReconciliationGetRiskInputReconResponses,
    ReconciliationGetRiskInputReconErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/recon/risk-input",
    ...options,
  });
};

/**
 * Get Pay To Hold
 */
export const portfolioToolsGetPayToHold = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetPayToHoldData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetPayToHoldResponses,
    PortfolioToolsGetPayToHoldErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/pay-to-hold",
    ...options,
  });
};

/**
 * Get Stock Borrow
 */
export const portfolioToolsGetStockBorrow = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetStockBorrowData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetStockBorrowResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/stock-borrow",
    ...options,
  });
};

/**
 * Get Reset Dates
 */
export const portfolioToolsGetResetDates = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetResetDatesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetResetDatesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/reset-dates",
    ...options,
  });
};

/**
 * Get Coming Resets
 */
export const portfolioToolsGetComingResets = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetComingResetsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetComingResetsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/coming-resets",
    ...options,
  });
};

/**
 * Get Cb Installments
 */
export const portfolioToolsGetCbInstallments = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetCbInstallmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetCbInstallmentsResponses,
    PortfolioToolsGetCbInstallmentsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/cb-installments",
    ...options,
  });
};

/**
 * Get Excess Amount
 */
export const portfolioToolsGetExcessAmount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetExcessAmountData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetExcessAmountResponses,
    PortfolioToolsGetExcessAmountErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/excess-amount",
    ...options,
  });
};

/**
 * Get Deal Indication
 */
export const portfolioToolsGetDealIndication = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetDealIndicationData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetDealIndicationResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/deal-indication",
    ...options,
  });
};

/**
 * Get Po Settlement
 */
export const portfolioToolsGetPoSettlement = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PortfolioToolsGetPoSettlementData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetPoSettlementResponses,
    PortfolioToolsGetPoSettlementErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/po-settlement",
    ...options,
  });
};

/**
 * Get Short Ecl
 */
export const portfolioToolsGetShortEcl = <ThrowOnError extends boolean = false>(
  options?: Options<PortfolioToolsGetShortEclData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PortfolioToolsGetShortEclResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/portfolio-tools/short-ecl",
    ...options,
  });
};

/**
 * Get Ticker Data
 */
export const instrumentsGetTickerData = <ThrowOnError extends boolean = false>(
  options?: Options<InstrumentsGetTickerDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    InstrumentsGetTickerDataResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/instruments/ticker-data",
    ...options,
  });
};

/**
 * Get Stock Screener
 */
export const instrumentsGetStockScreener = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<InstrumentsGetStockScreenerData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    InstrumentsGetStockScreenerResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/instruments/stock-screener",
    ...options,
  });
};

/**
 * Get Special Terms
 */
export const instrumentsGetSpecialTerms = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<InstrumentsGetSpecialTermsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    InstrumentsGetSpecialTermsResponses,
    InstrumentsGetSpecialTermsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/instruments/special-terms",
    ...options,
  });
};

/**
 * Get Instrument Data
 */
export const instrumentsGetInstrumentData = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<InstrumentsGetInstrumentDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    InstrumentsGetInstrumentDataResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/instruments/instrument-data",
    ...options,
  });
};

/**
 * Get Instrument Term
 */
export const instrumentsGetInstrumentTerm = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<InstrumentsGetInstrumentTermData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    InstrumentsGetInstrumentTermResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/instruments/instrument-term",
    ...options,
  });
};

/**
 * Get Event Calendar
 */
export const eventsGetEventCalendar = <ThrowOnError extends boolean = false>(
  options?: Options<EventsGetEventCalendarData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    EventsGetEventCalendarResponses,
    EventsGetEventCalendarErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/events/calendar",
    ...options,
  });
};

/**
 * Get Event Stream
 */
export const eventsGetEventStream = <ThrowOnError extends boolean = false>(
  options?: Options<EventsGetEventStreamData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    EventsGetEventStreamResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/events/stream",
    ...options,
  });
};

/**
 * Get Reverse Inquiries
 */
export const eventsGetReverseInquiries = <ThrowOnError extends boolean = false>(
  options?: Options<EventsGetReverseInquiriesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    EventsGetReverseInquiriesResponses,
    EventsGetReverseInquiriesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/events/reverse-inquiry",
    ...options,
  });
};

/**
 * Get Daily Procedures
 */
export const operationsGetDailyProcedures = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OperationsGetDailyProceduresData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OperationsGetDailyProceduresResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/operations/daily-procedures",
    ...options,
  });
};

/**
 * Get Operation Processes
 */
export const operationsGetOperationProcesses = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OperationsGetOperationProcessesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OperationsGetOperationProcessesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/operations/processes",
    ...options,
  });
};

/**
 * Rerun Process
 */
export const operationsRerunProcess = <ThrowOnError extends boolean = false>(
  options: Options<OperationsRerunProcessData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OperationsRerunProcessResponses,
    OperationsRerunProcessErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/operations/processes/{process_id}/rerun",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Kill Process
 */
export const operationsKillProcess = <ThrowOnError extends boolean = false>(
  options: Options<OperationsKillProcessData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OperationsKillProcessResponses,
    OperationsKillProcessErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/operations/processes/{process_id}/kill",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Orders
 */
export const ordersGetOrders = <ThrowOnError extends boolean = false>(
  options?: Options<OrdersGetOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetOrdersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/orders/",
    ...options,
  });
};

/**
 * Get Order Routes
 */
export const ordersGetOrderRoutes = <ThrowOnError extends boolean = false>(
  options?: Options<OrdersGetOrderRoutesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetOrderRoutesResponses,
    OrdersGetOrderRoutesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/orders/routes",
    ...options,
  });
};

/**
 * Get Kpi Data
 */
export const performanceGetKpiData = <ThrowOnError extends boolean = false>(
  options?: Options<PerformanceGetKpiDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PerformanceGetKpiDataResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/performance/kpi",
    ...options,
  });
};

/**
 * Get Top Movers
 */
export const performanceGetTopMovers = <ThrowOnError extends boolean = false>(
  options?: Options<PerformanceGetTopMoversData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PerformanceGetTopMoversResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/performance/top-movers",
    ...options,
  });
};

/**
 * Get Portfolio Holdings
 */
export const performanceGetPortfolioHoldings = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PerformanceGetPortfolioHoldingsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PerformanceGetPortfolioHoldingsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/performance/portfolio-holdings",
    ...options,
  });
};

/**
 * Get Notifications
 */
export const notificationsGetNotifications = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificationsGetNotificationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NotificationsGetNotificationsResponses,
    NotificationsGetNotificationsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/notifications/",
    ...options,
  });
};
