// This file is auto-generated by @hey-api/openapi-ts

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
};

/**
 * ItemRead
 */
export type ItemRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * Page[ItemRead]
 */
export type PageItemRead = {
  /**
   * Items
   */
  items: Array<ItemRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthAuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/jwt/login";
};

export type AuthAuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthAuthJwtLoginError =
  AuthAuthJwtLoginErrors[keyof AuthAuthJwtLoginErrors];

export type AuthAuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthAuthJwtLoginResponse =
  AuthAuthJwtLoginResponses[keyof AuthAuthJwtLoginResponses];

export type AuthAuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/logout";
};

export type AuthAuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthAuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: {
    detail?: string;
  };
};

export type AuthAuthJwtLogoutResponse =
  AuthAuthJwtLogoutResponses[keyof AuthAuthJwtLogoutResponses];

export type AuthRegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type AuthRegisterRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthRegisterRegisterError =
  AuthRegisterRegisterErrors[keyof AuthRegisterRegisterErrors];

export type AuthRegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type AuthRegisterRegisterResponse =
  AuthRegisterRegisterResponses[keyof AuthRegisterRegisterResponses];

export type AuthResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type AuthResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthResetForgotPasswordError =
  AuthResetForgotPasswordErrors[keyof AuthResetForgotPasswordErrors];

export type AuthResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type AuthResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type AuthResetResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthResetResetPasswordError =
  AuthResetResetPasswordErrors[keyof AuthResetResetPasswordErrors];

export type AuthResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthVerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/auth/request-verify-token";
};

export type AuthVerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthVerifyRequestTokenError =
  AuthVerifyRequestTokenErrors[keyof AuthVerifyRequestTokenErrors];

export type AuthVerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type AuthVerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type AuthVerifyVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthVerifyVerifyError =
  AuthVerifyVerifyErrors[keyof AuthVerifyVerifyErrors];

export type AuthVerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type AuthVerifyVerifyResponse =
  AuthVerifyVerifyResponses[keyof AuthVerifyVerifyResponses];

export type UsersUsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersUsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersUsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersCurrentUserResponse =
  UsersUsersCurrentUserResponses[keyof UsersUsersCurrentUserResponses];

export type UsersUsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersUsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersPatchCurrentUserError =
  UsersUsersPatchCurrentUserErrors[keyof UsersUsersPatchCurrentUserErrors];

export type UsersUsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersPatchCurrentUserResponse =
  UsersUsersPatchCurrentUserResponses[keyof UsersUsersPatchCurrentUserResponses];

export type UsersUsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersDeleteUserError =
  UsersUsersDeleteUserErrors[keyof UsersUsersDeleteUserErrors];

export type UsersUsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersUsersDeleteUserResponse =
  UsersUsersDeleteUserResponses[keyof UsersUsersDeleteUserResponses];

export type UsersUsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersUserError =
  UsersUsersUserErrors[keyof UsersUsersUserErrors];

export type UsersUsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersUserResponse =
  UsersUsersUserResponses[keyof UsersUsersUserResponses];

export type UsersUsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUsersPatchUserError =
  UsersUsersPatchUserErrors[keyof UsersUsersPatchUserErrors];

export type UsersUsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUsersPatchUserResponse =
  UsersUsersPatchUserResponses[keyof UsersUsersPatchUserResponses];

export type ItemReadItemData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/items/";
};

export type ItemReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemReadItemError = ItemReadItemErrors[keyof ItemReadItemErrors];

export type ItemReadItemResponses = {
  /**
   * Successful Response
   */
  200: PageItemRead;
};

export type ItemReadItemResponse =
  ItemReadItemResponses[keyof ItemReadItemResponses];

export type ItemCreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/items/";
};

export type ItemCreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemCreateItemError =
  ItemCreateItemErrors[keyof ItemCreateItemErrors];

export type ItemCreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemRead;
};

export type ItemCreateItemResponse =
  ItemCreateItemResponses[keyof ItemCreateItemResponses];

export type ItemDeleteItemData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/items/{item_id}";
};

export type ItemDeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemDeleteItemError =
  ItemDeleteItemErrors[keyof ItemDeleteItemErrors];

export type ItemDeleteItemResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PositionsGetPositionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Position Date
     * Position date (YYYY-MM-DD)
     */
    position_date?: string | null;
  };
  url: "/api/positions/";
};

export type PositionsGetPositionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PositionsGetPositionsError =
  PositionsGetPositionsErrors[keyof PositionsGetPositionsErrors];

export type PositionsGetPositionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PositionsGetStockPositionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Position Date
     */
    position_date?: string | null;
  };
  url: "/api/positions/stocks";
};

export type PositionsGetStockPositionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PositionsGetStockPositionsError =
  PositionsGetStockPositionsErrors[keyof PositionsGetStockPositionsErrors];

export type PositionsGetStockPositionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PositionsGetWarrantPositionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Position Date
     */
    position_date?: string | null;
  };
  url: "/api/positions/warrants";
};

export type PositionsGetWarrantPositionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PositionsGetWarrantPositionsError =
  PositionsGetWarrantPositionsErrors[keyof PositionsGetWarrantPositionsErrors];

export type PositionsGetWarrantPositionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PositionsGetBondPositionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Position Date
     */
    position_date?: string | null;
  };
  url: "/api/positions/bonds";
};

export type PositionsGetBondPositionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PositionsGetBondPositionsError =
  PositionsGetBondPositionsErrors[keyof PositionsGetBondPositionsErrors];

export type PositionsGetBondPositionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PositionsGetTradeSummaryData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
  };
  url: "/api/positions/trade-summary";
};

export type PositionsGetTradeSummaryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PositionsGetTradeSummaryError =
  PositionsGetTradeSummaryErrors[keyof PositionsGetTradeSummaryErrors];

export type PositionsGetTradeSummaryResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PnlGetPnlChangesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     * Trade date (YYYY-MM-DD)
     */
    trade_date?: string | null;
  };
  url: "/api/pnl/changes";
};

export type PnlGetPnlChangesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PnlGetPnlChangesError =
  PnlGetPnlChangesErrors[keyof PnlGetPnlChangesErrors];

export type PnlGetPnlChangesResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PnlGetPnlSummaryData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/pnl/summary";
};

export type PnlGetPnlSummaryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PnlGetPnlSummaryError =
  PnlGetPnlSummaryErrors[keyof PnlGetPnlSummaryErrors];

export type PnlGetPnlSummaryResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PnlGetPnlByCurrencyData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/pnl/currency";
};

export type PnlGetPnlByCurrencyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PnlGetPnlByCurrencyError =
  PnlGetPnlByCurrencyErrors[keyof PnlGetPnlByCurrencyErrors];

export type PnlGetPnlByCurrencyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PnlGetPnlFullData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/pnl/full";
};

export type PnlGetPnlFullErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PnlGetPnlFullError = PnlGetPnlFullErrors[keyof PnlGetPnlFullErrors];

export type PnlGetPnlFullResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PnlGetKpiMetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/pnl/kpi";
};

export type PnlGetKpiMetricsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetMarketDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/market-data/";
};

export type MarketDataGetMarketDataResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetFxDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/market-data/fx";
};

export type MarketDataGetFxDataResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetTopMoversData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Category
     * Category: ops, ytd, delta, price, volume
     */
    category?: "ops" | "ytd" | "delta" | "price" | "volume";
  };
  url: "/api/market-data/top-movers";
};

export type MarketDataGetTopMoversErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MarketDataGetTopMoversError =
  MarketDataGetTopMoversErrors[keyof MarketDataGetTopMoversErrors];

export type MarketDataGetTopMoversResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetTradingCalendarData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     * Start date (YYYY-MM-DD)
     */
    start_date?: string | null;
    /**
     * End Date
     * End date (YYYY-MM-DD)
     */
    end_date?: string | null;
  };
  url: "/api/market-data/trading-calendar";
};

export type MarketDataGetTradingCalendarErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MarketDataGetTradingCalendarError =
  MarketDataGetTradingCalendarErrors[keyof MarketDataGetTradingCalendarErrors];

export type MarketDataGetTradingCalendarResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetMarketHoursData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/market-data/market-hours";
};

export type MarketDataGetMarketHoursResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetTickerDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/market-data/ticker";
};

export type MarketDataGetTickerDataResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetHistoricalDataData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Tickers
     * Comma-separated ticker symbols
     */
    tickers?: string | null;
    /**
     * Start Date
     * Start date (YYYY-MM-DD)
     */
    start_date?: string | null;
    /**
     * End Date
     * End date (YYYY-MM-DD)
     */
    end_date?: string | null;
  };
  url: "/api/market-data/historical";
};

export type MarketDataGetHistoricalDataErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MarketDataGetHistoricalDataError =
  MarketDataGetHistoricalDataErrors[keyof MarketDataGetHistoricalDataErrors];

export type MarketDataGetHistoricalDataResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetStockDataData = {
  body?: never;
  path: {
    /**
     * Symbol
     */
    symbol: string;
  };
  query?: never;
  url: "/api/market-data/stock/{symbol}";
};

export type MarketDataGetStockDataErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MarketDataGetStockDataError =
  MarketDataGetStockDataErrors[keyof MarketDataGetStockDataErrors];

export type MarketDataGetStockDataResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetStockHistoryData = {
  body?: never;
  path: {
    /**
     * Symbol
     */
    symbol: string;
  };
  query?: {
    /**
     * Period
     * Period: 1mo, 3mo, 6mo, ytd, 1y, 2y, 5y, max
     */
    period?: "1mo" | "3mo" | "6mo" | "ytd" | "1y" | "2y" | "5y" | "max";
  };
  url: "/api/market-data/stock/{symbol}/history";
};

export type MarketDataGetStockHistoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MarketDataGetStockHistoryError =
  MarketDataGetStockHistoryErrors[keyof MarketDataGetStockHistoryErrors];

export type MarketDataGetStockHistoryResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarketDataGetStockNewsData = {
  body?: never;
  path: {
    /**
     * Symbol
     */
    symbol: string;
  };
  query?: never;
  url: "/api/market-data/stock/{symbol}/news";
};

export type MarketDataGetStockNewsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MarketDataGetStockNewsError =
  MarketDataGetStockNewsErrors[keyof MarketDataGetStockNewsErrors];

export type MarketDataGetStockNewsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RiskGetDeltaChangeData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/risk/delta-change";
};

export type RiskGetDeltaChangeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RiskGetDeltaChangeError =
  RiskGetDeltaChangeErrors[keyof RiskGetDeltaChangeErrors];

export type RiskGetDeltaChangeResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RiskGetRiskMeasuresData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/risk/measures";
};

export type RiskGetRiskMeasuresErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RiskGetRiskMeasuresError =
  RiskGetRiskMeasuresErrors[keyof RiskGetRiskMeasuresErrors];

export type RiskGetRiskMeasuresResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RiskGetRiskInputsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/risk/inputs";
};

export type RiskGetRiskInputsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RiskGetRiskInputsError =
  RiskGetRiskInputsErrors[keyof RiskGetRiskInputsErrors];

export type RiskGetRiskInputsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ComplianceGetRestrictedListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/compliance/restricted-list";
};

export type ComplianceGetRestrictedListResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ComplianceGetUndertakingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/compliance/undertakings";
};

export type ComplianceGetUndertakingsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ComplianceGetBeneficialOwnershipData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/compliance/beneficial-ownership";
};

export type ComplianceGetBeneficialOwnershipResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReconciliationGetPpsReconData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/recon/pps";
};

export type ReconciliationGetPpsReconErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReconciliationGetPpsReconError =
  ReconciliationGetPpsReconErrors[keyof ReconciliationGetPpsReconErrors];

export type ReconciliationGetPpsReconResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReconciliationGetSettlementReconData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/recon/settlement";
};

export type ReconciliationGetSettlementReconErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReconciliationGetSettlementReconError =
  ReconciliationGetSettlementReconErrors[keyof ReconciliationGetSettlementReconErrors];

export type ReconciliationGetSettlementReconResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReconciliationGetFailedTradesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/recon/failed-trades";
};

export type ReconciliationGetFailedTradesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReconciliationGetFailedTradesError =
  ReconciliationGetFailedTradesErrors[keyof ReconciliationGetFailedTradesErrors];

export type ReconciliationGetFailedTradesResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReconciliationGetPnlReconData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/recon/pnl";
};

export type ReconciliationGetPnlReconErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReconciliationGetPnlReconError =
  ReconciliationGetPnlReconErrors[keyof ReconciliationGetPnlReconErrors];

export type ReconciliationGetPnlReconResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReconciliationGetRiskInputReconData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Trade Date
     */
    trade_date?: string | null;
  };
  url: "/api/recon/risk-input";
};

export type ReconciliationGetRiskInputReconErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReconciliationGetRiskInputReconError =
  ReconciliationGetRiskInputReconErrors[keyof ReconciliationGetRiskInputReconErrors];

export type ReconciliationGetRiskInputReconResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PortfolioToolsGetPayToHoldData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/portfolio-tools/pay-to-hold";
};

export type PortfolioToolsGetPayToHoldResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PortfolioToolsGetStockBorrowData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/portfolio-tools/stock-borrow";
};

export type PortfolioToolsGetStockBorrowResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PortfolioToolsGetResetDatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/portfolio-tools/reset-dates";
};

export type PortfolioToolsGetResetDatesResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PortfolioToolsGetComingResetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/portfolio-tools/coming-resets";
};

export type PortfolioToolsGetComingResetsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PortfolioToolsGetCbInstallmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/portfolio-tools/cb-installments";
};

export type PortfolioToolsGetCbInstallmentsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PortfolioToolsGetExcessAmountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/portfolio-tools/excess-amount";
};

export type PortfolioToolsGetExcessAmountResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type InstrumentsGetTickerDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/instruments/ticker-data";
};

export type InstrumentsGetTickerDataResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type InstrumentsGetStockScreenerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/instruments/stock-screener";
};

export type InstrumentsGetStockScreenerResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type InstrumentsGetSpecialTermsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/instruments/special-terms";
};

export type InstrumentsGetSpecialTermsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EventsGetEventCalendarData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     * Start date (YYYY-MM-DD)
     */
    start_date?: string | null;
    /**
     * End Date
     * End date (YYYY-MM-DD)
     */
    end_date?: string | null;
  };
  url: "/api/events/calendar";
};

export type EventsGetEventCalendarErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EventsGetEventCalendarError =
  EventsGetEventCalendarErrors[keyof EventsGetEventCalendarErrors];

export type EventsGetEventCalendarResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EventsGetEventStreamData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/events/stream";
};

export type EventsGetEventStreamResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EventsGetReverseInquiriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Position Date
     * Position date (YYYY-MM-DD)
     */
    position_date?: string | null;
  };
  url: "/api/events/reverse-inquiry";
};

export type EventsGetReverseInquiriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EventsGetReverseInquiriesError =
  EventsGetReverseInquiriesErrors[keyof EventsGetReverseInquiriesErrors];

export type EventsGetReverseInquiriesResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OperationsGetDailyProceduresData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/operations/daily-procedures";
};

export type OperationsGetDailyProceduresResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OperationsGetOperationProcessesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/operations/processes";
};

export type OperationsGetOperationProcessesResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OrdersGetOrdersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/orders/";
};

export type OrdersGetOrdersResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OrdersGetOrderRoutesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Order Id
     * Optional EMSX order identifier
     */
    order_id?: number | null;
  };
  url: "/api/orders/routes";
};

export type OrdersGetOrderRoutesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OrdersGetOrderRoutesError =
  OrdersGetOrderRoutesErrors[keyof OrdersGetOrderRoutesErrors];

export type OrdersGetOrderRoutesResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PerformanceGetKpiDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/performance/kpi";
};

export type PerformanceGetKpiDataResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PerformanceGetTopMoversData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/performance/top-movers";
};

export type PerformanceGetTopMoversResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};
